1 / 0 rescue false # => false
=begin
ただいこの方法では、補足できる例外はStandardErrorとそのサブクラスに限られる

=end
